default:
    formatters:
        pretty:
            verbose: true
            paths: false
            snippets: false

    extensions:
        FriendsOfBehat\SymfonyExtension:
            kernel:
                class: AppKernel
                path: app/AppKernel.php
                bootstrap: behat-bootstrap.php

        FriendsOfBehat\ContextServiceExtension:
            imports:
                - "src/ImportDefinitionsBundle/Behat/Resources/config/services.yml"

        FriendsOfBehat\CrossContainerExtension: ~

        FriendsOfBehat\VariadicExtension: ~
