services:
    import_definitions.behat.filter.simple:
        class: ImportDefinitionsBundle\Behat\Service\Filter\SimpleFilter
        tags:
            - { name: import_definition.filter, type: simple }