jms_serializer:
    metadata:
        directories:
            import-definitions:
                namespace_prefix: "ImportDefinitionsBundle"
                path: "@ImportDefinitionsBundle/Resources/config/serializer"