services:
    import_definitions.behat.context.hook.pimcore_dao:
        class: ImportDefinitionsBundle\Behat\Context\Hook\PimcoreDaoContext
        arguments:
            - '@__symfony_shared__.doctrine.dbal.default_connection'
        tags:
            - { name: fob.context_service }

    import_definitions.behat.context.hook.pimcore_setup:
        class: ImportDefinitionsBundle\Behat\Context\Hook\PimcoreSetupContext
        tags:
            - { name: fob.context_service }

    import_definitions.behat.context.hook.im_setup:
        class: ImportDefinitionsBundle\Behat\Context\Hook\IMSetupContext
        tags:
            - { name: fob.context_service }
