services:
    import_definitions.behat.context.setup.pimcore_class:
        class: ImportDefinitionsBundle\Behat\Context\Setup\PimcoreClassContext
        arguments:
            - '@import_definitions.behat.shared_storage'
            - '@import_definitions.behat.class_storage'
        tags:
            - { name: fob.context_service }