services:
    import_definitions.behat.context.transform.pimcore_class:
        class: ImportDefinitionsBundle\Behat\Context\Transform\PimcoreClassContext
        arguments:
            - '@import_definitions.behat.shared_storage'
            - '@import_definitions.behat.class_storage'
        tags:
            - { name: fob.context_service }

    import_definitions.behat.context.transform.import_definition:
        class: ImportDefinitionsBundle\Behat\Context\Transform\ImportDefinitionContext
        arguments:
            - '@import_definitions.behat.shared_storage'
            - '@__symfony__.import_definitions.repository.definition'
        tags:
            - { name: fob.context_service }