services:
  Instride\Bundle\DataDefinitionsBundle\Command\ListImportDefinitionsCommand:
    arguments:
      - '@data_definitions.repository.import_definition'
    tags:
      - { name: 'console.command', command: 'data-definitions:list:imports' }

  Instride\Bundle\DataDefinitionsBundle\Command\ListExportDefinitionsCommand:
    arguments:
      - '@data_definitions.repository.export_definition'
    tags:
      - { name: 'console.command', command: 'data-definitions:list:exports' }

  Instride\Bundle\DataDefinitionsBundle\Command\ImportCommand:
    arguments:
      - '@event_dispatcher'
      - '@data_definitions.repository.import_definition'
      - '@Instride\Bundle\DataDefinitionsBundle\Importer\ImporterInterface'
    tags:
      - { name: 'console.command', command: 'data-definitions:import' }

  Instride\Bundle\DataDefinitionsBundle\Command\ImportAsyncCommand:
    arguments:
      - '@event_dispatcher'
      - '@data_definitions.repository.import_definition'
      - '@Instride\Bundle\DataDefinitionsBundle\Importer\ImporterInterface'
    tags:
      - { name: 'console.command', command: 'data-definitions:async-import' }

  Instride\Bundle\DataDefinitionsBundle\Command\ExportCommand:
    arguments:
      - '@event_dispatcher'
      - '@data_definitions.repository.export_definition'
      - '@Instride\Bundle\DataDefinitionsBundle\Exporter\ExporterInterface'
    tags:
      - { name: 'console.command', command: 'data-definitions:export' }

  Instride\Bundle\DataDefinitionsBundle\Command\ImportImportDefinitionCommand:
    arguments:
      - '@=service("CoreShop\\Component\\Resource\\Metadata\\RegistryInterface").get("data_definitions.import_definition")'
      - '@data_definitions.repository.import_definition'
      - '@CoreShop\Bundle\ResourceBundle\Pimcore\ObjectManager'
      - '@CoreShop\Bundle\ResourceBundle\Controller\ResourceFormFactoryInterface'
    tags:
      - { name: 'console.command', command: 'data-definitions:definition:import:import' }

  Instride\Bundle\DataDefinitionsBundle\Command\ImportExportDefinitionCommand:
    arguments:
      - '@=service("CoreShop\\Component\\Resource\\Metadata\\RegistryInterface").get("data_definitions.export_definition")'
      - '@data_definitions.repository.export_definition'
      - '@CoreShop\Bundle\ResourceBundle\Pimcore\ObjectManager'
      - '@CoreShop\Bundle\ResourceBundle\Controller\ResourceFormFactoryInterface'
    tags:
      - { name: 'console.command', command: 'data-definitions:definition:import:export' }

  Instride\Bundle\DataDefinitionsBundle\Command\ConvertExportDefinitionsToYaml:
    tags:
      - { name: 'console.command', command: 'data-definition:configuration:exporter:convert-to-yaml' }

  Instride\Bundle\DataDefinitionsBundle\Command\ConvertImportDefinitionsToYaml:
    tags:
      - { name: 'console.command', command: 'data-definition:configuration:importer:convert-to-yaml' }