services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Instride\Bundle\DataDefinitionsBundle\Installer:
    public: true
    arguments:
      $bundle: "@=service('kernel').getBundle('DataDefinitionsBundle')"
