services:
  Instride\Bundle\DataDefinitionsBundle\ProcessManager\ProcessManagerImportListener:
    arguments:
      - '@process_manager.factory.process'
      - '@ProcessManagerBundle\Logger\ProcessLogger'
      - '@process_manager.repository.process'
      - '@event_dispatcher'
    tags:
      - { name: 'kernel.event_listener', event: 'data_definitions.import.total', method: 'onTotalEvent' }
      - { name: 'kernel.event_listener', event: 'data_definitions.import.progress', method: 'onProgressEvent' }
      - { name: 'kernel.event_listener', event: 'data_definitions.import.status', method: 'onStatusEvent' }
      - { name: 'kernel.event_listener', event: 'data_definitions.import.finished', method: 'onFinishedEvent' }
      - { name: 'kernel.event_listener', event: 'data_definitions.import.failure', method: 'onFailureEvent' }

  Instride\Bundle\DataDefinitionsBundle\ProcessManager\ProcessManagerExportListener:
    arguments:
      - '@process_manager.factory.process'
      - '@ProcessManagerBundle\Logger\ProcessLogger'
      - '@process_manager.repository.process'
      - '@event_dispatcher'
    calls:
      - method: setProviderRegistry
        arguments:
          - '@data_definitions.registry.export_provider'
    tags:
      - { name: 'kernel.event_listener', event: 'data_definitions.export.total', method: 'onTotalEvent' }
      - { name: 'kernel.event_listener', event: 'data_definitions.export.progress', method: 'onProgressEvent' }
      - { name: 'kernel.event_listener', event: 'data_definitions.export.status', method: 'onStatusEvent' }
      - { name: 'kernel.event_listener', event: 'data_definitions.export.finished', method: 'onFinishedEvent' }
      - { name: 'kernel.event_listener', event: 'data_definitions.export.failure', method: 'onFailureEvent' }

  Instride\Bundle\DataDefinitionsBundle\ProcessManager\ImportDefinitionProcess:
    tags:
      - { name: 'process_manager.process', type: 'importdefinition', form-type: Instride\Bundle\DataDefinitionsBundle\Form\Type\ProcessManager\ImportDefinitionsType }

  Instride\Bundle\DataDefinitionsBundle\ProcessManager\ExportDefinitionProcess:
    tags:
      - { name: 'process_manager.process', type: 'exportdefinition', form-type: Instride\Bundle\DataDefinitionsBundle\Form\Type\ProcessManager\ImportDefinitionsType }

  Instride\Bundle\DataDefinitionsBundle\ProcessManager\ExportDefinitionStartupFormResolver:
    arguments:
      - '@data_definitions.repository.export_definition'
    tags:
      - { name: 'process_manager.startup_form_resolver', type: 'exportdefinition' }

  Instride\Bundle\DataDefinitionsBundle\ProcessManager\ImportDefinitionsReport:
    tags:
      - { name: process_manager.process_report, type: import_definitions }
